### ISSUE TITLE
Support for Postgres 10

### ISSUE THREAD

**Issue by vsapucaia** [gasparesganga/postgis-normalize-geometry#2] opened 2018-03-22 15:42 UTC
This function doesn't work anymore on Postgres 10, since now they are not allowing anymore SRF inside CASE statements. 

Here is the error message:
[0A000] ERROR: set-returning functions are not allowed in CASE
Hint: You might be able to move the set-returning function into a LATERAL FROM item.

**Comment by gasparesganga** [comment] 2018-03-22 16:16
I think the problem is related to `ST_Dump` and `ST_DumpRings`, but I will need to test it with a PostgreSQL 10 & PostGIS 2.4 environment.
Unfortunately I don't have any available at the moment, but it is high in my priorities.
Thank you for your feedback, I'll try to fix it asap (I mean, days)!

**Comment by gasparesganga** [comment] 2018-07-18 07:09
Hi again.
I'm sorry it took me more time than expected, but sometime *life gets in the way*, you know...

I'm just committed a fix for this, but it needs some fine tuning to address an annoying behaviour of the pl/pgSQL query planner which caches a wrong plan when the function is used on a set of geometries of mixed types and the number of each type differ by a consistent margin. 
If you are using the function on a single type of geometries (ie. `POLYGONS` and `MULTIPOLYGONS`, or `LINESTRINGS` and `MULTILINESTRINGS`) then it works just fine and you can use the unreleased code (it's already committed in the repository).

**Comment by gasparesganga** [comment] 2018-07-18 08:46
I've just released v1.2.0 which is 100% PostgreSQL 10 compatible.
I forgot to reference this issue in the commit, so I am manually closing this issue.

Thank you for your feedback, I'm sorry it took much longer than expected to fix it.

**Closed as completed by gasparesganga** 2018-07-18 08:46 UTC

**Comment by sroze** [comment] 2018-07-19 08:09
Thank you for fixing it :)
